name: CI

on: [push, pull_request]

jobs:
  build_xbox_pro_strings_con:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Onyx
        run: |
          sudo apt install wget
          sudo wget -P dependencies https://github.com/mtolly/onyxite-customs/releases/download/20230130/onyx-20230130-linux-x64.AppImage
          ls dependencies
          chmod +x dependencies/onyx-20230130-linux-x64.AppImage
          ./onyx-20230130-linux-x64.AppImage stfs


  # build_xbox_standard:
  #   runs-on: ubuntu-latest

  # https://github.com/mtolly/onyxite-customs/releases/download/20230130/onyx-20230130-linux-x64.AppImage

    # steps:
    #   - uses: actions/checkout@v3
    #   - name: Set up Python 3.9
    #     uses: actions/setup-python@v4
    #     with:
    #       python-version: '3.9'
    #   - name: Set env
    #     run: |
    #       echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
    #       echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
    #       chmod +x dependencies/arkhelper
    #       chmod +x dependencies/dtab
    #       chmod +x dependencies/superfreq
    #       pip install gitpython
  #         pip install mido
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Remove PS3 files
  #       run: |
  #         find . -name "*.*_ps3" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-Xbox-Base
  #         path: _build/xbox

  # build_xbox_original_mids:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Revert mid updates to their originals
  #       run: |
  #         find _ark/songs/updates/ -name "*.mid" -type f -delete
  #         find _ark/songs/updates/ -empty -type d -delete
  #     - name: Disable mid updates in dta
  #       run: |
  #         python dependencies/dev_scripts/disable_chart_updates.py
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Remove PS3 files
  #       run: |
  #         find . -name "*.*_ps3" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-Xbox-original-mids
  #         path: _build/xbox

  # build_xbox_keys:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Add rb3_plus keys into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_keys.py
  #     - name: Remove PS3 files
  #       run: |
  #         find . -name "*.*_ps3" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/xbox/gen -n "patch_xbox" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-Xbox-keys
  #         path: _build/xbox

  # build_ps3_standard:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Remove Xbox files
  #       run: |
  #         find . -name "*.*_xbox" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-PS3-Base
  #         path: _build/ps3

  # build_ps3_original_mids:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Revert mid updates to their originals
  #       run: |
  #         find _ark/songs/updates/ -name "*.mid" -type f -delete
  #         find _ark/songs/updates/ -empty -type d -delete
  #     - name: Disable mid updates in dta
  #       run: |
  #         python dependencies/dev_scripts/disable_chart_updates.py
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Remove Xbox files
  #       run: |
  #         find . -name "*.*_xbox" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/ps3/gen -n "patch_ps3" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-PS3-original-mids
  #         path: _build/ps3

  # build_ps3_keys:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set up Python 3.9
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Add rb3_plus keys into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_keys.py
  #     - name: Remove Xbox files
  #       run: |
  #         find . -name "*.*_xbox" -type f -delete
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6
      
  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-PS3-keys
  #         path: _build/ps3

  # build_ps3_stock_inst_mapping:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install mido
  #         pip install gitpython
  #     - name: Set env
  #       run: |
  #         echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-7)" >> $GITHUB_ENV
  #         echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
  #         chmod +x dependencies/arkhelper
  #         chmod +x dependencies/dtab
  #         chmod +x dependencies/superfreq
  #         pip install gitpython
  #         pip install mido
  #     - name: Add rb3_plus pro strings into the patch ark
  #       run: |
  #         python dependencies/dev_scripts/add_rb3_plus_pro_strings.py
  #     - name: Remove Xbox files
  #       run: |
  #         find . -name "*.*_xbox" -type f -delete
  #     - name: Restore stock instrument mapping
  #       run: |
  #         python dependencies/dev_scripts/enable_stock_pad.py
  #     - name: Print build info
  #       run: |
  #         echo $GITHUB_SHA_SHORT
  #         python dependencies/dev_scripts/add_devbuild.py $GITHUB_SHA_SHORT
  #     - name: Build ARK
  #       run: |
  #         dependencies/arkhelper dir2ark ./_ark ./_build/ps3/USRDIR/gen -n "patch_ps3" -e -v 6

  #     - name: Upload result
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: RB3DX-PS3-stock-instrument-mapping
  #         path: _build/ps3
